//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanSystem.Client.LoanService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoanService.ILoans")]
    public interface ILoans {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoans/GetLoans", ReplyAction="http://tempuri.org/ILoans/GetLoansResponse")]
        string GetLoans();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoans/GetLoans", ReplyAction="http://tempuri.org/ILoans/GetLoansResponse")]
        System.Threading.Tasks.Task<string> GetLoansAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoans/CreateLoan", ReplyAction="http://tempuri.org/ILoans/CreateLoanResponse")]
        System.Guid CreateLoan(string loanName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoans/CreateLoan", ReplyAction="http://tempuri.org/ILoans/CreateLoanResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateLoanAsync(string loanName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoansChannel : LoanSystem.Client.LoanService.ILoans, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoansClient : System.ServiceModel.ClientBase<LoanSystem.Client.LoanService.ILoans>, LoanSystem.Client.LoanService.ILoans {
        
        public LoansClient() {
        }
        
        public LoansClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoansClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoansClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoansClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLoans() {
            return base.Channel.GetLoans();
        }
        
        public System.Threading.Tasks.Task<string> GetLoansAsync() {
            return base.Channel.GetLoansAsync();
        }
        
        public System.Guid CreateLoan(string loanName) {
            return base.Channel.CreateLoan(loanName);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateLoanAsync(string loanName) {
            return base.Channel.CreateLoanAsync(loanName);
        }
    }
}
