//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanSystem.WpfClient.LoanService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loan", Namespace="http://schemas.datacontract.org/2004/07/LoanSystem.Api")]
    [System.SerializableAttribute()]
    public partial class Loan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MaturityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Maturity {
            get {
                return this.MaturityField;
            }
            set {
                if ((this.MaturityField.Equals(value) != true)) {
                    this.MaturityField = value;
                    this.RaisePropertyChanged("Maturity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoanService.ILoans")]
    public interface ILoans {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoans/CreateLoan", ReplyAction="http://tempuri.org/ILoans/CreateLoanResponse")]
        int CreateLoan(LoanSystem.WpfClient.LoanService.Loan loan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoans/CreateLoan", ReplyAction="http://tempuri.org/ILoans/CreateLoanResponse")]
        System.Threading.Tasks.Task<int> CreateLoanAsync(LoanSystem.WpfClient.LoanService.Loan loan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoans/GetLoans", ReplyAction="http://tempuri.org/ILoans/GetLoansResponse")]
        string GetLoans();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoans/GetLoans", ReplyAction="http://tempuri.org/ILoans/GetLoansResponse")]
        System.Threading.Tasks.Task<string> GetLoansAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoansChannel : LoanSystem.WpfClient.LoanService.ILoans, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoansClient : System.ServiceModel.ClientBase<LoanSystem.WpfClient.LoanService.ILoans>, LoanSystem.WpfClient.LoanService.ILoans {
        
        public LoansClient() {
        }
        
        public LoansClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoansClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoansClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoansClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateLoan(LoanSystem.WpfClient.LoanService.Loan loan) {
            return base.Channel.CreateLoan(loan);
        }
        
        public System.Threading.Tasks.Task<int> CreateLoanAsync(LoanSystem.WpfClient.LoanService.Loan loan) {
            return base.Channel.CreateLoanAsync(loan);
        }
        
        public string GetLoans() {
            return base.Channel.GetLoans();
        }
        
        public System.Threading.Tasks.Task<string> GetLoansAsync() {
            return base.Channel.GetLoansAsync();
        }
    }
}
